import "server-only";

import { parseServerEnvironment } from "@/lib/config/env-schema";

export const serverEnvironment = parseServerEnvironment({
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  OPENAI_MODEL: process.env.OPENAI_MODEL,
  OPENAI_ENABLED: process.env.OPENAI_ENABLED,
  OPENAI_REQUEST_TIMEOUT_MS: process.env.OPENAI_REQUEST_TIMEOUT_MS,
  OPENAI_MAX_OUTPUT_TOKENS: process.env.OPENAI_MAX_OUTPUT_TOKENS,
  OPENAI_MAX_TOOL_CALLS: process.env.OPENAI_MAX_TOOL_CALLS,
  OPENAI_HISTORY_MESSAGE_LIMIT: process.env.OPENAI_HISTORY_MESSAGE_LIMIT,
  OPENAI_INPUT_CHARACTER_BUDGET: process.env.OPENAI_INPUT_CHARACTER_BUDGET,
  APP_BASE_URL: process.env.APP_BASE_URL,
  PUBLIC_RATE_LIMIT_SECRET: process.env.PUBLIC_RATE_LIMIT_SECRET,
  PUBLIC_CLIENT_IP_HEADER: process.env.PUBLIC_CLIENT_IP_HEADER,
});
