import "server-only";

import { parseServerEnvironment } from "@/lib/config/env-schema";

export const serverEnvironment = parseServerEnvironment({
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  OPENAI_MODEL: process.env.OPENAI_MODEL,
  OPENAI_ENABLED: process.env.OPENAI_ENABLED,
  OPENAI_REQUEST_TIMEOUT_MS: process.env.OPENAI_REQUEST_TIMEOUT_MS,
  OPENAI_MAX_OUTPUT_TOKENS: process.env.OPENAI_MAX_OUTPUT_TOKENS,
  OPENAI_MAX_TOOL_CALLS: process.env.OPENAI_MAX_TOOL_CALLS,
  OPENAI_HISTORY_MESSAGE_LIMIT: process.env.OPENAI_HISTORY_MESSAGE_LIMIT,
  OPENAI_INPUT_CHARACTER_BUDGET: process.env.OPENAI_INPUT_CHARACTER_BUDGET,
  APP_BASE_URL: process.env.APP_BASE_URL,
  PUBLIC_RATE_LIMIT_SECRET: process.env.PUBLIC_RATE_LIMIT_SECRET,
  PUBLIC_CLIENT_IP_HEADER: process.env.PUBLIC_CLIENT_IP_HEADER,
  ATTACHMENT_ALLOW_UNSCANNED: process.env.ATTACHMENT_ALLOW_UNSCANNED,
  META_WHATSAPP_ENABLED: process.env.META_WHATSAPP_ENABLED,
  META_GRAPH_API_VERSION: process.env.META_GRAPH_API_VERSION,
  META_APP_ID: process.env.META_APP_ID,
  META_APP_SECRET: process.env.META_APP_SECRET,
  META_WHATSAPP_VERIFY_TOKEN: process.env.META_WHATSAPP_VERIFY_TOKEN,
  META_WHATSAPP_ACCESS_TOKEN: process.env.META_WHATSAPP_ACCESS_TOKEN,
  META_WHATSAPP_PHONE_NUMBER_ID: process.env.META_WHATSAPP_PHONE_NUMBER_ID,
  META_WHATSAPP_BUSINESS_ACCOUNT_ID:
    process.env.META_WHATSAPP_BUSINESS_ACCOUNT_ID,
  META_WHATSAPP_TEST_RECIPIENT: process.env.META_WHATSAPP_TEST_RECIPIENT,
  META_WHATSAPP_REQUEST_TIMEOUT_MS:
    process.env.META_WHATSAPP_REQUEST_TIMEOUT_MS,
  META_WHATSAPP_MAX_WEBHOOK_BYTES: process.env.META_WHATSAPP_MAX_WEBHOOK_BYTES,
});
